trigger:
  - master

resources:
  - repo: self

variables:
  tag: 105
  #"$(Build.BuildId)"

stages:
# Stage 1
# Build Docker Image
# Publish the k8s Files
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          # - task: Docker@2
          #   displayName: Build an image
          #   inputs:
          #     containerRegistry: "manish-docker-hub"
          #     repository: "manish98dangi/currency-exchange-devops"
          #     command: "buildAndPush"
          #     Dockerfile: "**/Dockerfile"
          #     tags: "$(tag)"
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: '**/*.yaml'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'manifests'
              publishLocation: 'Container'


# Stage 2 
# Download the k8s Files
# Deploy to k8s Cluster with Image
  - stage: Deploy
    displayName: Deploy
    jobs:
      - job: Deploy
        displayName: Deploy
        pool:
          vmImage: "ubuntu-latest"
        steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            artifactName: 'manifests'
            itemPattern: '**/*.yaml'
            targetPath: '$(System.ArtifactsDirectory)'
        - task: KubernetesManifest@0
          inputs:
            action: 'deploy'
            kubernetesServiceConnection: 'azure-kubernetes-connection'
            namespace: 'default'
            manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
            containers: 'manish98dangi/currency-exchange-devops:$(tag)'
